## place this file in /etc/pipewire/pipewire.conf.d/10-vlx-chromium-sink.conf
## then systemctl --user restart pipewire pipewire-pulse
## a simple check: pw-cli dump short Node | grep vlx_chromium_sink

context.modules = [
    { name = libpipewire-module-adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "vlx_chromium_sink"
            node.description = "VLX_Chromium"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
        }
    }
]
